export const SAMPLE_DATA = [
    {
        id: 1,
        name: "John Doe",
        email: "john.doe@example.com",
        age: 28,
        department: "Engineering",
        salary: 75000,
        isActive: true,
        joinDate: "2022-03-15",
        skills: ["JavaScript", "React", "Node.js"],
        address: { city: "New York", country: "USA" },
    },
    {
        id: 2,
        name: "Jane Smith",
        email: "jane.smith@example.com",
        age: 32,
        department: "Marketing",
        salary: 68000,
        isActive: true,
        joinDate: "2021-07-22",
        skills: ["SEO", "Content Marketing", "Analytics"],
        address: { city: "Los Angeles", country: "USA" },
    },
    {
        id: 3,
        name: "Mike Johnson",
        email: "mike.johnson@example.com",
        age: 35,
        department: "Engineering",
        salary: 82000,
        isActive: false,
        joinDate: "2020-11-08",
        skills: ["Python", "Django", "PostgreSQL"],
        address: { city: "Chicago", country: "USA" },
    },
    {
        id: 4,
        name: "Sarah Wilson",
        email: "sarah.wilson@example.com",
        age: 29,
        department: "Design",
        salary: 71000,
        isActive: true,
        joinDate: "2022-01-10",
        skills: ["Figma", "Adobe Creative Suite", "UI/UX"],
        address: { city: "San Francisco", country: "USA" },
    },
    {
        id: 5,
        name: "David Brown",
        email: "david.brown@example.com",
        age: 41,
        department: "Sales",
        salary: 85000,
        isActive: true,
        joinDate: "2019-05-14",
        skills: ["CRM", "Lead Generation", "Negotiation"],
        address: { city: "Miami", country: "USA" },
    },
    {
        id: 6,
        name: "Emily Davis",
        email: "emily.davis@example.com",
        age: 26,
        department: "Engineering",
        salary: 73000,
        isActive: true,
        joinDate: "2023-02-28",
        skills: ["TypeScript", "Vue.js", "MongoDB"],
        address: { city: "Seattle", country: "USA" },
    },
    {
        id: 7,
        name: "Robert Miller",
        email: "robert.miller@example.com",
        age: 38,
        department: "Marketing",
        salary: 72000,
        isActive: false,
        joinDate: "2020-09-03",
        skills: ["PPC", "Social Media", "Brand Management"],
        address: { city: "Boston", country: "USA" },
    },
    {
        id: 8,
        name: "Lisa Anderson",
        email: "lisa.anderson@example.com",
        age: 33,
        department: "HR",
        salary: 65000,
        isActive: true,
        joinDate: "2021-12-01",
        skills: ["Recruitment", "Employee Relations", "Training"],
        address: { city: "Austin", country: "USA" },
    },
    {
        id: 9,
        name: "James Taylor",
        email: "james.taylor@example.com",
        age: 30,
        department: "Engineering",
        salary: 78000,
        isActive: true,
        joinDate: "2022-06-18",
        skills: ["Java", "Spring Boot", "Microservices"],
        address: { city: "Denver", country: "USA" },
    },
    {
        id: 10,
        name: "Maria Garcia",
        email: "maria.garcia@example.com",
        age: 27,
        department: "Design",
        salary: 69000,
        isActive: true,
        joinDate: "2023-01-05",
        skills: ["Sketch", "Prototyping", "User Research"],
        address: { city: "Portland", country: "USA" },
    },
    {
        id: 11,
        name: "Christopher Lee",
        email: "christopher.lee@example.com",
        age: 36,
        department: "Sales",
        salary: 79000,
        isActive: true,
        joinDate: "2020-04-12",
        skills: ["B2B Sales", "Account Management", "Presentations"],
        address: { city: "Phoenix", country: "USA" },
    },
    {
        id: 12,
        name: "Amanda White",
        email: "amanda.white@example.com",
        age: 31,
        department: "Marketing",
        salary: 70000,
        isActive: false,
        joinDate: "2021-08-25",
        skills: ["Email Marketing", "Automation", "A/B Testing"],
        address: { city: "Nashville", country: "USA" },
    },
    {
        id: 13,
        name: "Daniel Martinez",
        email: "daniel.martinez@example.com",
        age: 34,
        department: "Engineering",
        salary: 81000,
        isActive: true,
        joinDate: "2021-03-07",
        skills: ["C#", ".NET", "Azure"],
        address: { city: "Dallas", country: "USA" },
    },
    {
        id: 14,
        name: "Jessica Thompson",
        email: "jessica.thompson@example.com",
        age: 28,
        department: "HR",
        salary: 63000,
        isActive: true,
        joinDate: "2022-10-14",
        skills: ["Payroll", "Benefits Administration", "Compliance"],
        address: { city: "Atlanta", country: "USA" },
    },
    {
        id: 15,
        name: "Kevin Rodriguez",
        email: "kevin.rodriguez@example.com",
        age: 39,
        department: "Sales",
        salary: 87000,
        isActive: true,
        joinDate: "2019-02-20",
        skills: ["Enterprise Sales", "Strategic Planning", "Team Leadership"],
        address: { city: "Las Vegas", country: "USA" },
    },
    {
        id: 16,
        name: "Michelle Clark",
        email: "michelle.clark@example.com",
        age: 25,
        department: "Design",
        salary: 66000,
        isActive: true,
        joinDate: "2023-04-03",
        skills: ["Illustration", "Branding", "Motion Graphics"],
        address: { city: "San Diego", country: "USA" },
    },
    {
        id: 17,
        name: "Ryan Lewis",
        email: "ryan.lewis@example.com",
        age: 42,
        department: "Engineering",
        salary: 95000,
        isActive: true,
        joinDate: "2018-11-30",
        skills: ["DevOps", "Kubernetes", "CI/CD"],
        address: { city: "Minneapolis", country: "USA" },
    },
    {
        id: 18,
        name: "Nicole Walker",
        email: "nicole.walker@example.com",
        age: 29,
        department: "Marketing",
        salary: 67000,
        isActive: true,
        joinDate: "2022-05-16",
        skills: ["Content Strategy", "Copywriting", "Webinars"],
        address: { city: "Tampa", country: "USA" },
    },
    {
        id: 19,
        name: "Brandon Hall",
        email: "brandon.hall@example.com",
        age: 33,
        department: "Sales",
        salary: 76000,
        isActive: false,
        joinDate: "2021-01-28",
        skills: ["Inside Sales", "Cold Calling", "Pipeline Management"],
        address: { city: "Orlando", country: "USA" },
    },
    {
        id: 20,
        name: "Stephanie Young",
        email: "stephanie.young@example.com",
        age: 37,
        department: "HR",
        salary: 71000,
        isActive: true,
        joinDate: "2020-07-09",
        skills: ["Performance Management", "Organizational Development", "Coaching"],
        address: { city: "Charlotte", country: "USA" },
    },
    {
        id: 21,
        name: "Gregory King",
        email: "gregory.king@example.com",
        age: 31,
        department: "Engineering",
        salary: 77000,
        isActive: true,
        joinDate: "2022-09-12",
        skills: ["React Native", "Mobile Development", "Firebase"],
        address: { city: "Salt Lake City", country: "USA" },
    },
    {
        id: 22,
        name: "Rachel Wright",
        email: "rachel.wright@example.com",
        age: 26,
        department: "Design",
        salary: 68000,
        isActive: true,
        joinDate: "2023-03-21",
        skills: ["Web Design", "Responsive Design", "CSS"],
        address: { city: "Kansas City", country: "USA" },
    },
    {
        id: 23,
        name: "Jonathan Lopez",
        email: "jonathan.lopez@example.com",
        age: 40,
        department: "Sales",
        salary: 89000,
        isActive: true,
        joinDate: "2019-08-17",
        skills: ["Channel Sales", "Partner Management", "Revenue Growth"],
        address: { city: "Columbus", country: "USA" },
    },
    {
        id: 24,
        name: "Samantha Hill",
        email: "samantha.hill@example.com",
        age: 32,
        department: "Marketing",
        salary: 74000,
        isActive: true,
        joinDate: "2021-11-04",
        skills: ["Product Marketing", "Go-to-Market", "Competitive Analysis"],
        address: { city: "Indianapolis", country: "USA" },
    },
    {
        id: 25,
        name: "Andrew Scott",
        email: "andrew.scott@example.com",
        age: 35,
        department: "Engineering",
        salary: 83000,
        isActive: false,
        joinDate: "2020-12-15",
        skills: ["Machine Learning", "Data Science", "Python"],
        address: { city: "Milwaukee", country: "USA" },
    },
    {
        id: 26,
        name: "Kimberly Green",
        email: "kimberly.green@example.com",
        age: 28,
        department: "HR",
        salary: 64000,
        isActive: true,
        joinDate: "2022-08-07",
        skills: ["Talent Acquisition", "Onboarding", "HRIS"],
        address: { city: "Memphis", country: "USA" },
    },
    {
        id: 27,
        name: "Matthew Adams",
        email: "matthew.adams@example.com",
        age: 44,
        department: "Sales",
        salary: 92000,
        isActive: true,
        joinDate: "2018-06-23",
        skills: ["Sales Management", "Team Building", "Forecasting"],
        address: { city: "Louisville", country: "USA" },
    },
    {
        id: 28,
        name: "Ashley Baker",
        email: "ashley.baker@example.com",
        age: 30,
        department: "Design",
        salary: 72000,
        isActive: true,
        joinDate: "2022-02-11",
        skills: ["Product Design", "Design Systems", "Accessibility"],
        address: { city: "Richmond", country: "USA" },
    },
    {
        id: 29,
        name: "Joshua Nelson",
        email: "joshua.nelson@example.com",
        age: 27,
        department: "Engineering",
        salary: 74000,
        isActive: true,
        joinDate: "2023-05-08",
        skills: ["Go", "Docker", "API Development"],
        address: { city: "Raleigh", country: "USA" },
    },
    {
        id: 30,
        name: "Megan Carter",
        email: "megan.carter@example.com",
        age: 34,
        department: "Marketing",
        salary: 73000,
        isActive: true,
        joinDate: "2021-04-19",
        skills: ["Marketing Automation", "Lead Nurturing", "ROI Analysis"],
        address: { city: "Birmingham", country: "USA" },
    },
]
